ConnectSmartConsulting/Controllers/FreeResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConnectSmartConsulting.Controllers
{
    public class FreeResourcesController : Controller
    {
        [ActionName("index")]
        public ActionResult Index()
        {
            return View("index");
        }

        [ActionName("resource-links")]
        public ActionResult ResourceLinks()
        {
            return View("ResourceLinks");
        }


        [ActionName("add")]
        public ActionResult Add()
        {
            return View("add");
        }
    }
}

ConnectSmartConsulting/Controllers/SmartLearningController.cs
using ConnectSC.Models;
using ConnectSmartConsulting.Helpers;
using ConnectSmartConsulting.Models;
using System;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace ConnectSmartConsulting.Controllers
{
    public class SmartLearningController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        #region Login
        public ActionResult Login(string msg)
        {
            if (!string.IsNullOrEmpty(msg))
            {
                if(msg.Equals("register_success"))
                {
                    ViewBag.Message = "You have been registered successfully, but your account pending approval. Kindly check your inbox for updates.";
                }
                else
                {
                    ViewBag.Message = "You have been logged out successfully";
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users user)
        {
            try
            {
                //var data = userModule.GetAllUser();
                //var selectedData = data.Where(m => m.UserName.Equals(user.UserName)).FirstOrDefault();
                var selectedData = userModule.AuthenticateUser(user.UserName, user.Password);

                if (selectedData != null)
                {
                    if (selectedData.IsApproved == false)
                    {
                        ViewBag.Registration = "Your account is pending approval. Kindly check your inbox after some time.";
                            //"You may contact administrator - admin@connectsmartconsulting.com";
                        return View();
                    }
                    if (selectedData.IsActive.Equals(true) && selectedData.IsApproved.Equals(true))
                    {
                        Session["LOGIN_USER"] = selectedData;

                        switch (selectedData.Role)
                        {
                            case (int)URole.Admin:
                                return RedirectToAction("index", "admin");
                            case (int)URole.Tutor:
                                return RedirectToAction("index", "tutor");
                            case (int)URole.Student:
                                return RedirectToAction("index", "student");
                        }
                    }
                    else
                    {
                        ViewBag.Registration = "User is not approved or activated";
                        ViewBag.Result = "Error";
                    }
                }
                else
                {
                    ViewBag.Registration = "Email Or Password is invalid";
                    ViewBag.Result = "Error";

                }
            }
            catch (Exception ex)
            {
                log.Error("Error Message in SmartLearning Controller Login !" + ex);
            }
            return View();
        }
        #endregion

        #region Register
        [ActionName("need-a-tutor")]
        public ActionResult Register()
        {
            return View("Register");
        }

        [HttpPost]
        public ActionResult Register(UserDetails userDetails)
        {
            try
            {
                if (ValidateMailByEmail(userDetails.Email))
                {
                    userDetails.Role = 3;
                    var data = userModule.AddUserDetails(userDetails);
                    if (data)
                    {
                        string subject = "Registrated Successfully.";
                        string Name = userDetails.FirstName;
                        string Pass = userDetails.LastName;
                        string body = "Thanks for registering with us.";
                        SendRegisterMail(userDetails.Email, subject, body, Name, Pass);
                    }
                    return RedirectToAction("Login", new { msg = "register_success" });
                }
                else
                {
                    ViewBag.Registration = "Email is Already Registered.";
                    ViewBag.Result = "Error";
                }
            }
            catch (Exception ex)
            {
                log.Error("Error Message in SmartLearning Controller Register !" + ex);
            }
            return View();
        }
        #endregion

        #region Forgot Password
        public ActionResult ForgotPassword()
        {
            ViewBag.Result = " ";
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(string Email)
        {
            try
            {
                var password = System.Web.Security.Membership.GeneratePassword(8, 1);
                string subject = "Forgot Password.";
                string body = "Your Password for ConnectSmartConsulting is:  " + password;
                SendForgotPasswordMail(Email, subject, password);
                ViewBag.Result = "Message";

            }
            catch (Exception ex)
            {
                log.Error("Error Message in SmartLearning Controller ForgotPassword !" + ex);
            }

            return View();
        }
        #endregion

        #region Change Password
        [ActionName("change-password")]
        public ActionResult ChangePassword()
        {
            if (Session["LOGIN_USER"] == null)
                return RedirectToAction("login", new { msg = "log_out" });

            return View("ChangePassword");
        }
        #endregion

        #region Tutor Registration
        [ActionName("tutor-registration")]
        public ActionResult TutorRegister()
        {
            return View("TutorRegister");
        }

        [HttpPost]
        public ActionResult TutorRegister(UserDetails userDetails)
        {
            try
            {
                if (ValidateMailByEmail(userDetails.Email))
                {
                    userDetails.Role = 2;
                    var data = userModule.AddUserDetails(userDetails);
                    if (data)
                    {
                        string subject = "Registered  Successfully.";
                        string body = "Thanks for registering with us.";
                        SendRegisterMail(userDetails.Email, subject, body, userDetails.FirstName, userDetails.Pass);
                    }
                    return RedirectToAction("Login", new { msg = "register_success" });
                }
                else
                {
                    ViewBag.Registration = "Email is Already Registered.";
                    ViewBag.Result = "Error";
                }
            }
            catch (Exception ex)
            {
                //log.Debug("Debug Message!");
                //log.Warn("Warn Message!");
                log.Error("Error Message in SmartLearning Controller TutorRegister !" + ex);
                // log.Fatal("Fatal Message!");
                // throw ex;
            }
            return View();

        }
        #endregion

        #region Free Resources
        [ActionName("free-resources")]
        public ActionResult FreeResource()
        {
            //if (HttpContext.Cache["email"] == null)
            //{
            //    ViewBag.email = null;
            //}
            return View("FreeResource");
        }

        [HttpPost]
        public ActionResult FreeResource(UserDetails userDetails)
        {
            if (HttpContext.Cache["email"] == null)
            {
                HttpContext.Cache["email"] = userDetails.Email;
            }

            ViewBag.email = HttpContext.Cache["email"];
            return View();
        }
        #endregion

        #region Smart Team
        [ActionName("smart-team")]
        public ActionResult SmartTeam()
        {
            return View("SmartTeam");
        }

        #endregion

        #region Logout
        public ActionResult Logout()
        {
            Session["LOGIN_USER"] = null;
            Session.Remove("LOGIN_USER");
            Session.Abandon();

            return RedirectToAction("login", new { msg = "loggedout" });
        }
        #endregion

        //public JsonResult GetAllCountries()
        //{
        //    var objDict = new Dictionary<string, string>();
        //    try
        //    {

        //        foreach (var cultureInfo in CultureInfo.GetCultures(CultureTypes.SpecificCultures))
        //        {
        //            var regionInfo = new RegionInfo(cultureInfo.Name);
        //            if (!objDict.ContainsKey(regionInfo.EnglishName))
        //            {
        //                objDict.Add(regionInfo.EnglishName, regionInfo.TwoLetterISORegionName.ToLower());
        //            }
        //        }
        //        var obj = objDict.OrderBy(p => p.Key).ToArray();


        //    }
        //    catch (Exception ex)
        //    {

        //        log.Error("Error Message in SmartLearning Controller GetAllCountries !" + ex);

        //    }
        //    return Json(obj.Select(t => new
        //    {
        //        Text = t.Key,
        //        Value = t.Value
        //    }), JsonRequestBehavior.AllowGet);
        //}

        #region Contact
        public ActionResult SmartLearningContact()
        {
            ContactDetails ContactDetails = new ContactDetails
            {
                SelectedService = "Smart Learning"
            };
            return View(ContactDetails);
        }

        [HttpPost]
        public ActionResult SmartLearningContact(ContactDetails ContactDetails)
        {
            string body = "";
            try
            {
                #region sending Enquiry mail to customer
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Template/Enquiry.html")))
                {
                    body = reader.ReadToEnd();
                }

ConnectSmartConsulting/Views/SmartLearning/ChangePassword.cshtml
@{
    ViewBag.Title = "EditTutor";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Content("~/admin/dash")">Home</a></li>
            <li class="breadcrumb-item active">Change Password</li>
        </ul>
    </div>
</div>

<section class="forms">
    <div class="container-fluid">
        <header>
            <h1 class="h3 display pull-left">Change Password</h1>
            <div class="pull-right">
                <a href="@Url.Content("~/admin/dash")"> Back</a>
            </div>
        </header>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-block">
                        @using (Html.BeginForm("change-password", "SmartLearning", FormMethod.Post, new { id = "frmCP", @class = "col-md-12" }))
                        {
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="OldPassword">Old Password</label>
                                    <input type="password" name="OldPassword" placeholder="Old Password" id="OldPassword" class="form-control" required />
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="NewPassword">New Password</label>
                                    <input type="password" name="NewPassword" placeholder="New Password" id="NewPassword" class="form-control" required />
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="ConfirmPassword">Confirm New Password</label>
                                    <input type="password" name="ConfirmPassword" placeholder="Confirm Password" id="ConfirmPassword" class="form-control" required />
                                </div>
                            </div>
                            <input type="hidden" name="UserKey" value="@(((ConnectSmartConsulting.Models.LoggedInUser)Session["LOGIN_USER"]).UserKey)" />
                            <button type="submit" class="btn btn-primary">Submit</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts
{
    <script src="@Url.Content("~/js/cpwd.js")" type="text/javascript"></script>
}

ConnectSmartConsulting/Views/SmartLearning/ForgotPassword.cshtml
@{
    ViewBag.Title = "ForgotPassword";
    Layout = "~/Views/Shared/_LayoutSmartLearning.cshtml";
}
<link href="~/Content/SmartlearningCustom.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
@*<script src="~/Scripts/Customjs/jquery-2.1.3.min.js"></script>*@
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
<h2>Forgot Password</h2>

@using (Html.BeginForm("ForgotPassword", "SmartLearning", FormMethod.Post, new { id = "msform" }))
{
    
    
      if(Request.HttpMethod=="GET")
         {
             ViewBag.Result = " ";

          }
      else
      {
          
          
      }
    
<!-- multistep form -->
    @*<form id="msform">*@
    <!-- progressbar -->
    <!-- fieldsets -->
    <fieldset>
        <h2 class="fs-title">Forgot Password</h2>
		<form>
            <input type="email" name="Email" placeholder="Email" required />
        <input type="submit" name="ForgotPassword" class="next action-button" value="Submit"/>
		</form>
		<div class="clear"></div>
        @*<span class='pull-right control-group'>Password has been sent to your register email address.</span>*@
    </fieldset>
    @*</form>*@
}
<script>
    $(document).ready(function () {
	 var myJsVariable = '@ViewBag.Result' 
        if(myJsVariable!= " ")
        {
            alertify.set('notifier', 'position', 'top-center');
            alertify.success('Password has been sent to your register email address.');
        }

    });
</script>

ConnectSmartConsulting/Views/SmartLearning/FreeResource - Copy.cshtml
@{
    ViewBag.Title = "Free Resource";
    Layout = "~/Views/Shared/_LayoutSmartLearning.cshtml";
}
<section>
    <div class="container">
        <div class="p-xl-5">
            <div style="margin:30px 0 0 0">
            </div>
        </div>
    </div>
</section>
<main id="main">
    <section id="portfolio" class="section-bg">
        @using (Html.BeginForm("FreeResource", "SmartLearning", FormMethod.Post))
    {
        <div class="container">
            <div class="col-md-6 col-md-offset-3">
                <div>
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="modal fade" tabindex="-1" id="loginModal"
                                     data-keyboard="false" data-backdrop="static">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal">
                                                    ×
                                                </button>
                                                <h4 class="modal-title">Free Resource Login</h4>
                                            </div>
                                            <div class="modal-body">



                                                <div class="form-group">
                                                    <input class="form-control" type="text" name="Email"
                                                           placeholder="EmailID" />
                                                </div>
                                                <div class="form-group">
                                                    <input class="form-control" placeholder="Phone" name="PhoneNumber"
                                                           type="number" />
                                                </div>



                                            </div>
                                            <div style="text-align:center;padding-bottom: 10px;">
                                                <button type="submit" id="btnsubmit" class="btn btn-success button button4">
                                                    Subscribe
                                                </button>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- JS includes -->
        <script src="https://code.jquery.com/jquery-1.11.3.js"></script>
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <!-- CSS Includes -->
        <link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />
        <div class="container">
            <div class="section-container pure-g">
                <div class="bottom-section container-fixed pure-u-7-8 pure-u-md-11-12">
                    <h2 class="title">
                        NCERT Solutions for Maths &amp; Science Books
                    </h2>
                    <p class="description" itemprop="description">
                        We provide you the detailed solutions for all questions from NCERT or CBSE text book as per CCE marking scheme pattern, to help you in day to day learning and excel in term end or year end examinations conducted by CBSE.
                        NCERT solutions provide detailed, step-by-step solutions to all questions in an NCERT textbook. They are an invaluable aid to students when they need help with their homework, while preparing for exams and while learning.
                        If you face issues or find difficult to answer or solve questions from NCERT books or you find it diffcult to understand how to approach a problem , Vedantu is one stop solution.
                        NCERT Solutions for class 6, 7, 8, 9, 10 , 11 &amp; 12 can be access through  the links below.
                    </p>
                    <div class="links">

                    </div>
                </div>
            </div>
        </div>
        <div class="content-flex">
            <div class="content-container pure-u-1">
                <div class="section-container pure-g">
                    <div class="section container-fixed pure-u-7-8 pure-u-md-11-12">
                        <div class="section-container pure-g">
                            <div class="section section-modules pure-u-1 pure-u-lg-17-24 pure-u-xl-3-4">
                                <div class="modules pure-g">

                                    <div class="module-container pure-u-1 pure-u-md-1-2">
                                        <div class="module" itemprop="articleSection">

                                            <ul></ul>
                                        </div>
                                    </div>

                                    <div class="module-container pure-u-1 pure-u-md-1-2">
                                        <div class="module" itemprop="articleSection">
                                            <h3 class=""></h3>
                                            <ul></ul>
                                        </div>
                                    </div>


                                </div>
                            </div>
                            <div class="section-container pure-u-1 pure-u-lg-7-24 pure-u-xl-1-4">
                                <div class="section section-sidebars pure-g">

                                    <div class="module-container sidebar-container pure-u-1 pure-u-sm-1 pure-u-md-1-2 pure-u-lg-1">
                                        <div class="sidebar" itemprop="articleSection">
                                            <h3 class=""></h3>
                                            <ul></ul>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
}
    </section>
        

</main>
<section>
    <div class="container">
        <div class="p-xl-5">
        </div>
    </div>
</section>
<script type="text/javascript" language="javascript">
$("#btnsubmit").click(function () {
    $("#loginModal").modal('hide');
});
$(document).ready(function () {
    debugger;
    var email='@ViewBag.email';
    if (email == "")
    {
        $("#loginModal").modal('show');
    }
});
</script>

ConnectSmartConsulting/Views/SmartLearning/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutSmartLearning.cshtml";
}



<div class="top-content csl-registration">
    <div class="container csl-loginformholder">
        <!-- MultiStep Form -->
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 text-center">
                @if (ViewBag.Message != null)
                {
                    <div class="alert">
                        <div class="alert-success">
                            <p style="padding:10px">@ViewBag.Message</p>
                        </div>
                    </div>
                }

            </div>
            <div class="col-md-6 col-md-offset-3">


                <form id="msform">
                    <!-- fieldsets -->
                    <div id="errormessage"></div>
                    @using (Html.BeginForm("Login", "SmartLearning", FormMethod.Post, new { id = "msform", @class = "form" }))
                    {
                    <fieldset>
                        <h2 class="fs-title">LOGIN</h2>
                        <input type="email" name="UserName" placeholder="Your Email" class="csl-email form-control" id="txtemail" required="required">
                        <div class="validation"></div>
                        <input type="password" name="Password" class="csl-password form-control" id="txtpass" placeholder="Your Password" pattern=".{6,}" required="required" title="6 characters minimum">
                        <div class="validation"></div>

                        @*<button type="submit" name="login" class="submit action-button" value="Login" id="btnLogin" />*@
                        <button type="submit" name="login" class="btn btn-info btn-sm" value="Login" id="btnLogin">Login</button>
                        <div class="col-md-5"><a href='@Url.Action("ForgotPassword", "SmartLearning")'>Forgot password</a></div>
                    </fieldset>
                    }
                </form>

            </div>
        </div>
        <!-- /.MultiStep Form -->


    </div>
</div>
<!--Login page ends-->

@section scripts{
    <script>
        var baseURL = '@System.Configuration.ConfigurationManager.AppSettings["ApiUrl"]';
    </script>
    <script src="@Url.Content("~/js/common.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/js/login.js")?" @DateTime.Now.Ticks type="text/javascript"></script>
}

ConnectSmartConsulting/Views/SmartLearning/Login_old.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutSmartLearning.cshtml";
}
<link href="~/Content/SmartlearningCustom.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
@*<script src="~/Scripts/Customjs/jquery-2.1.3.min.js"></script>*@
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js'></script>
<style>
    /*#divProcessing {
position: absolute;
top: 50%;
left: 50%;
margin: -50px 0px 0px -50px;
}
    #msform {
position: relative;
}*/

    .modal {
            position: fixed;
            z-index: 999;
            height: 100%;
            width: 100%;
            top: 0;
            background-color: Black;
            filter: alpha(opacity=60);
            opacity: 0.6;
            -moz-opacity: 0.8;
            display: none;
        }
        .center {
            position: absolute;
top: 50%;
left: 50%;
margin: -50px 0px 0px -50px;
            z-index: 1000;
            /*margin: 50px auto;*/
            /*padding: 10px;
            width: 130px;*/
            /*background-color: transparent;*/
            /*border-radius: 10px;
            filter: alpha(opacity=100);
            opacity: 1;
            -moz-opacity: 1;*/
        }

</style>

@using (Html.BeginForm("Login", "SmartLearning", FormMethod.Post, new { id = "msform" }))
{
	if(Request.HttpMethod=="GET")
         {
             ViewBag.Result = " ";
          }
<!-- multistep form -->
@*<form id="msform">*@
    <!-- progressbar -->
    <!-- fieldsets -->
    <fieldset>
        <h2 class="fs-title">Login your account</h2>
        <input type="text" name="UserName" placeholder="Email" required/>
        <input type="password" name="Password" placeholder="Password" required/>
        <input type="submit" name="login" class="next action-button" value="Login" id="btnLogin"/>
		<div class="clear"></div>
		<span class='pull-right control-group'><a href='@Url.Action("ForgotPassword", "SmartLearning")'><span>Forgot Password</span></a></span>
		<span class='pull-left control-group'><a href='@Url.Action("Register", "SmartLearning")'><span>Register</span></a>
		</span>
    </fieldset>
    <div id="divProcessing" hidden="hidden" class="modal">
        <div class="center"><img src="~/Images/Preloader_3.gif" /></div>  

    </div>
@*</form>*@
}
<script>
    $(document).ready(function () {
        var myJsVariable = '@ViewBag.Registration';
        var result = '@ViewBag.Result';
        if(myJsVariable!= "")
        {
            if (result == "Success") {
                alertify.set('notifier', 'position', 'top-center');
                alertify.success(myJsVariable);
            }
            else {
                alertify.set('notifier', 'position', 'top-center');
                alertify.error(myJsVariable);

            }
           
        }



    });


    $('#btnLogin').click(function () {
        $('#divProcessing').show();
    });
</script>

ConnectSmartConsulting/Views/SmartLearning/Notifications.cshtml
@{
    ViewBag.Title = "Notifications";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="@Url.Content("~/admin/dash")">Home</a></li>
            <li class="breadcrumb-item active">Notifications</li>
        </ul>
    </div>
</div>
<section class="charts">
    <div class="container-fluid">
        <header>
            <h1 class="h3 display pull-left">Notifications</h1>
          
        </header>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-block">
                        <div class="table-responsive">
                            <h2 class="text-muted">No new Notifications</h2>
                            <!-- /.table-responsive -->
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

ConnectSmartConsulting/Views/SmartLearning/SmartTeam.cshtml
@{
    ViewBag.Title = "SmartTeam";
    Layout = "~/Views/Shared/_LayoutSmartLearning.cshtml";
}

<main id="main">
    <!--==========================
      Team Section
    ============================-->
    @Html.Partial("_Team")
    <!-- #team -->
</main>