ConnectSmartConsulting/Controllers/FreeResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConnectSmartConsulting.Controllers
{
    public class FreeResourcesController : Controller
    {
        [ActionName("index")]
        public ActionResult Index()
        {
            return View("index");
        }

        [ActionName("resource-links")]
        public ActionResult ResourceLinks()
        {
            return View("ResourceLinks");
        }


        [ActionName("add")]
        public ActionResult Add()
        {
            return View("add");
        }
    }
}

ConnectSmartConsulting/Controllers/ServiceRequestController.cs
using ConnectSC.Data.Models;
using ConnectSC.Models;
using ConnectSmartConsulting.Helpers;
using ConnectSmartConsulting.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;
using ConnectSC.Data.ViewModels;

namespace ConnectSmartConsulting.Controllers
{
    public class ServiceRequestController : BaseController
    {
        [ActionName("add")]
        public ActionResult Add()
        {
            if (Session["LOGIN_USER"] != null)
            {
                var usr = (LoggedInUser)Session["LOGIN_USER"];
                return View(usr);
            }
            return RedirectToAction("Login", "SmartLearning");
        }

        [HttpPost]
        [ActionName("add")]
        public ActionResult Add(ServiceTicket model)
        {
            var usr = (LoggedInUser)Session["LOGIN_USER"];

            var serviceTicket = new ServiceTicket
            {
                Category = model.Category,
                Description = model.Description,
                UserID = usr.UserId,
                TicketDate = DateTime.UtcNow.AddHours(5).AddMinutes(30),
                AttachmentPath = string.Empty
            };

            HttpClientHelper<ServiceTicket> helper = new HttpClientHelper<ServiceTicket>();
            helper.Post(serviceTicket, "tickets/post?userKey=" + LoggedInUser.UserKey);

            return RedirectToAction("index");
        }

        [ActionName("index")]
        public ActionResult Index(string searchFilter)
        {
            HttpClientHelper<ServiceTicketViewModel> helper = new HttpClientHelper<ServiceTicketViewModel>();

            if (Session["LOGIN_USER"] != null)
            {
                var userData = (LoggedInUser)Session["LOGIN_USER"];

                searchFilter = searchFilter ?? "";
                var tickets = helper.Get(string.Format("tickets/search?userId={0}&rowCount=0&searchFilter={1}", userData.UserId, searchFilter));

                ViewBag.SearchFilter = searchFilter;
                return View("index", tickets);
            }

            return RedirectToAction("login", new { msg = "loggedout" });
        }

        [ActionName("show")]
        public ActionResult Show(int? id)
        {
            if (Session["LOGIN_USER"] != null)
            {
                var usr = (LoggedInUser)Session["LOGIN_USER"];
                return View(usr);
            }
            return RedirectToAction("Login", "SmartLearning");
        }
    }
}

ConnectSmartConsulting/Controllers/SmartLearningController.cs
using ConnectSC.Models;
using ConnectSmartConsulting.Helpers;
using ConnectSmartConsulting.Models;
using System;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace ConnectSmartConsulting.Controllers
{
    public class SmartLearningController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        #region Login
        public ActionResult Login(string msg)
        {
            if (!string.IsNullOrEmpty(msg))
            {
                if(msg.Equals("register_success"))
                {
                    ViewBag.Message = "You have been registered successfully, but your account pending approval. Kindly check your inbox for updates.";
                }
                else
                {
                    ViewBag.Message = "You have been logged out successfully";
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users user)
        {
            try
            {
                //var data = userModule.GetAllUser();
                //var selectedData = data.Where(m => m.UserName.Equals(user.UserName)).FirstOrDefault();
                var selectedData = userModule.AuthenticateUser(user.UserName, user.Password);

                if (selectedData != null)
                {
                    if (selectedData.IsApproved == false)
                    {
                        ViewBag.Registration = "Your account is pending approval. Kindly check your inbox after some time.";
                            //"You may contact administrator - admin@connectsmartconsulting.com";
                        return View();
                    }
                    if (selectedData.IsActive.Equals(true) && selectedData.IsApproved.Equals(true))
                    {
                        Session["LOGIN_USER"] = selectedData;

                        switch (selectedData.Role)
                        {
                            case (int)URole.Admin:
                                return RedirectToAction("index", "admin");
                            case (int)URole.Tutor:
                                return RedirectToAction("index", "tutor");
                            case (int)URole.Student:
                                return RedirectToAction("index", "student");
                        }
                    }
                    else
                    {
                        ViewBag.Registration = "User is not approved or activated";
                        ViewBag.Result = "Error";
                    }
                }
                else
                {
                    ViewBag.Registration = "Email Or Password is invalid";
                    ViewBag.Result = "Error";

                }
            }
            catch (Exception ex)
            {
                log.Error("Error Message in SmartLearning Controller Login !" + ex);
            }
            return View();
        }
        #endregion

        #region Register
        [ActionName("need-a-tutor")]
        public ActionResult Register()
        {
            return View("Register");
        }

        [HttpPost]
        public ActionResult Register(UserDetails userDetails)
        {
            try
            {
                if (ValidateMailByEmail(userDetails.Email))
                {
                    userDetails.Role = 3;
                    var data = userModule.AddUserDetails(userDetails);
                    if (data)
                    {
                        string subject = "Registrated Successfully.";
                        string Name = userDetails.FirstName;
                        string Pass = userDetails.LastName;
                        string body = "Thanks for registering with us.";
                        SendRegisterMail(userDetails.Email, subject, body, Name, Pass);
                    }
                    return RedirectToAction("Login", new { msg = "register_success" });
                }
                else
                {
                    ViewBag.Registration = "Email is Already Registered.";
                    ViewBag.Result = "Error";
                }
            }
            catch (Exception ex)
            {
                log.Error("Error Message in SmartLearning Controller Register !" + ex);
            }
            return View();
        }
        #endregion

        #region Forgot Password
        public ActionResult ForgotPassword()
        {
            ViewBag.Result = " ";
            return View();
        }

        [HttpPost]
        public ActionResult ForgotPassword(string Email)
        {
            try
            {
                var password = System.Web.Security.Membership.GeneratePassword(8, 1);
                string subject = "Forgot Password.";
                string body = "Your Password for ConnectSmartConsulting is:  " + password;
                SendForgotPasswordMail(Email, subject, password);
                ViewBag.Result = "Message";

            }
            catch (Exception ex)
            {
                log.Error("Error Message in SmartLearning Controller ForgotPassword !" + ex);
            }

            return View();
        }
        #endregion

        #region Change Password
        [ActionName("change-password")]
        public ActionResult ChangePassword()
        {
            if (Session["LOGIN_USER"] == null)
                return RedirectToAction("login", new { msg = "log_out" });

            return View("ChangePassword");
        }
        #endregion

        #region Tutor Registration
        [ActionName("tutor-registration")]
        public ActionResult TutorRegister()
        {
            return View("TutorRegister");
        }

        [HttpPost]
        public ActionResult TutorRegister(UserDetails userDetails)
        {
            try
            {
                if (ValidateMailByEmail(userDetails.Email))
                {
                    userDetails.Role = 2;
                    var data = userModule.AddUserDetails(userDetails);
                    if (data)
                    {
                        string subject = "Registered  Successfully.";
                        string body = "Thanks for registering with us.";
                        SendRegisterMail(userDetails.Email, subject, body, userDetails.FirstName, userDetails.Pass);
                    }
                    return RedirectToAction("Login", new { msg = "register_success" });
                }
                else
                {
                    ViewBag.Registration = "Email is Already Registered.";
                    ViewBag.Result = "Error";
                }
            }
            catch (Exception ex)
            {
                //log.Debug("Debug Message!");
                //log.Warn("Warn Message!");
                log.Error("Error Message in SmartLearning Controller TutorRegister !" + ex);
                // log.Fatal("Fatal Message!");
                // throw ex;
            }
            return View();

        }
        #endregion

        #region Free Resources
        [ActionName("free-resources")]
        public ActionResult FreeResource()
        {
            //if (HttpContext.Cache["email"] == null)
            //{
            //    ViewBag.email = null;
            //}
            return View("FreeResource");
        }

        [HttpPost]
        public ActionResult FreeResource(UserDetails userDetails)
        {
            if (HttpContext.Cache["email"] == null)
            {
                HttpContext.Cache["email"] = userDetails.Email;
            }

            ViewBag.email = HttpContext.Cache["email"];
            return View();
        }
        #endregion

        #region Smart Team
        [ActionName("smart-team")]
        public ActionResult SmartTeam()
        {
            return View("SmartTeam");
        }

        #endregion

        #region Logout
        public ActionResult Logout()
        {
            Session["LOGIN_USER"] = null;
            Session.Remove("LOGIN_USER");
            Session.Abandon();

            return RedirectToAction("login", new { msg = "loggedout" });
        }
        #endregion

        //public JsonResult GetAllCountries()
        //{
        //    var objDict = new Dictionary<string, string>();
        //    try
        //    {

        //        foreach (var cultureInfo in CultureInfo.GetCultures(CultureTypes.SpecificCultures))
        //        {
        //            var regionInfo = new RegionInfo(cultureInfo.Name);
        //            if (!objDict.ContainsKey(regionInfo.EnglishName))
        //            {
        //                objDict.Add(regionInfo.EnglishName, regionInfo.TwoLetterISORegionName.ToLower());
        //            }
        //        }
        //        var obj = objDict.OrderBy(p => p.Key).ToArray();


        //    }
        //    catch (Exception ex)
        //    {

        //        log.Error("Error Message in SmartLearning Controller GetAllCountries !" + ex);

        //    }
        //    return Json(obj.Select(t => new
        //    {
        //        Text = t.Key,
        //        Value = t.Value
        //    }), JsonRequestBehavior.AllowGet);
        //}

        #region Contact
        public ActionResult SmartLearningContact()
        {
            ContactDetails ContactDetails = new ContactDetails
            {
                SelectedService = "Smart Learning"
            };
            return View(ContactDetails);
        }

        [HttpPost]
        public ActionResult SmartLearningContact(ContactDetails ContactDetails)
        {
            string body = "";
            try
            {
                #region sending Enquiry mail to customer
                using (StreamReader reader = new StreamReader(Server.MapPath("~/Template/Enquiry.html")))
                {
                    body = reader.ReadToEnd();
                }

ConnectSmartConsulting/Views/Shared/ComingSoon.cshtml
@{
    //ViewBag.Title = "Free Resource";
    Layout = "~/Views/Shared/_LayoutSmartLearning.cshtml";
}
<section>
    <div class="container">
        <div class="p-xl-5">
            <div style="margin:30px 0 0 0">
            </div>
        </div>
    </div>
</section>
<main id="main">
    <section id="portfolio" class="section-bg">
        <div class="bgimg">
            <div class="middle">
                <h1>COMING SOON ...</h1>
                <hr>
            </div>

        </div>
    </section>
</main>
<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    .bgimg {
        background-image: url('/w3images/forestbridge.jpg');
        height: 100%;
        background-position: center;
        background-size: cover;
        position: relative;
        color: darkorange;
        font-family: "Courier New", Courier, monospace;
        font-size: 25px;
    }

    .topleft {
        position: absolute;
        top: 0;
        left: 16px;
    }

    .bottomleft {
        position: absolute;
        bottom: 0;
        left: 16px;
    }

    .middle {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
    }

    hr {
        margin: auto;
        width: 40%;
    }
</style>

ConnectSmartConsulting/Views/Shared/_Featured.cshtml
<section id="featured-services">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 box">
                <i class=" ion-android-chat"></i>
                <h4 class="title"><a href="">Personalized Live Training</a></h4>
                @*<p class="description">Content here...</p>*@
                <ul>
                    <li>Dedicated Teacher</li>
                    <li>Teaching at student's pace</li>
                </ul>
            </div>
            <div class="col-lg-4 box box-bg">
                <i class=" ion-android-checkmark-circle "></i>
                <h4 class="title"><a href="">Safety &amp; Security</a></h4>
                <ul>
                    <li>Learn @@ safety of home</li>
                    <li>No traffic annoyance</li>
                </ul>
            </div>
            <div class="col-lg-4 box">
                <i class="ion-android-alarm-clock"></i>
                <h4 class="title"><a href="">Anytime Learning</a></h4>
                <ul>
                    <li>Choose your own topic/time &amp; pace</li>
                    <li>Choice of Web and Mobile Platform</li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 box-bg">
                <i class="ion-ios-stopwatch-outline"></i>
                <h4 class="title"><a href="">Save on Time</a></h4>
                <ul>
                    <li>No commuting</li>
                    <li>No looking out for the right teacher</li>
                </ul>
            </div>
            <div class="col-lg-4 box box">
                <i class="ion-android-bulb"></i>
                <h4 class="title"><a href="">Better than recorded lectures</a></h4>
                <ul>
                    <li>2 way interaction</li>
                    <li>Monitoring &amp; Counseling</li>
                </ul>
            </div>
            
        </div>
    </div>
</section>

ConnectSmartConsulting/Views/Shared/_Footer.cshtml
<div class="container-fluid csl-footer">
    <div class="container">

        <div class="row">
            <div class="col-xs-12 col-md-4 col-sm-12 col-lg-4 csl-footer-intro">
                <img src="/content/images/connect-smart-learning-logo.png">
                <p>
                    INVENT THE FUTURE with the right guidance,design thinking and innovative solutions for Digital transformation.<br />
                    <br />
                    CONNECT SMART technology advisory services will help transform your business through the management and implementation of new apps,
                    platforms, architecture and tech. We’ll partner with you to determine the right combination of technologies
                    for your business—from the tech that exists today to the emerging tech of tomorrow.
                </p>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 col-lg-4">
                <h3>Useful Links</h3>
                <ul>
                    <li><i class="ion-ios-arrow-right"></i> <a href="@Url.Content("~/home/index")">Home</a></li>
                    <li><i class="ion-ios-arrow-right"></i> <a href="@Url.Content("~/home/index#about")">About us</a></li>
                    <li><i class="ion-ios-arrow-right"></i> <a href="@Url.Content("~/home/smart-learning")">Smart Learning</a></li>
                    <li><i class="ion-ios-arrow-right"></i> <a href="@Url.Content("~/home/smart-jobs")">Smart Jobs</a></li>
                    <li><i class="ion-ios-arrow-right"></i> <a href="@Url.Content("~/home/ComingSoon")">Terms of service</a></li>
                    <li><i class="ion-ios-arrow-right"></i> <a href="@Url.Content("~/home/ComingSoon")">Privacy policy</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-md-4 col-sm-6 col-lg-4">
                <h3>Contact us</h3>
                <p>
                    <b>Hyderabad</b><br />
                    2-48/97, Telecom Nagar<br />
                    Gachi Bowli, Hyderabad
                    India
                </p><br />
                <br />
                <p>
                    <b>Chandigarh</b><br />
                    SCO 11, 2nd Floor<br />
                    Phase 5 Indl Area, Mohali (Chandigarh Tricity Region)
                    India <br />
                    <br />
                    <span class="glyphicon glyphicon-earphone"> </span>+91 96182 42427 <br />
                    <span class="glyphicon glyphicon-envelope"> </span> support@connectsmartconsulting.com
                </p>
            </div>
        </div>
    </div>
    <hr />
    <div class="container-fluid csl-copyright text-center"><p>&copy; Copyright 2018 Connect Smart Consulting. All Rights Reserved</p></div>
</div>

ConnectSmartConsulting/Views/Shared/_Header.cshtml
<header id="header">
    <div class="container-fluid">
        <div id="logo" class="pull-left">
            <a href="@Url.Content("~/home/index")">
                <img src="/images/main_logo1.png"style="width:180px;margin-top:-5px;" alt="Connect Smart Consulting" title="Connect Smart Consulting" />
            </a>
        </div>
        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li class="menu-active"><a href="@Url.Content("~/home/index")">Home</a></li>
                <li class="menu-has-children">
                    <a href="javascript:;">Our Capabilities</a>
                    <ul>
                        <li>
                            <a href='@Url.Action("software-Engineering", "Home")'>Smart Engineering (Agile Practices)</a>
                        </li>
                        <li>
                            <a href='@Url.Action("software-reseller","Home")'>Software Resellers</a>
                        </li>
                        <li>
                            <a href='@Url.Action("sales-and-digital-marketing","Home")'>Sales & Digital Marketing</a>
                        </li>
                        <li>
                            <a href='@Url.Action("erp-consulting","Home")'>ERP Consulting</a>
                        </li>
                        <li>
                            <a href='@Url.Action("application-support-maintenance","Home")'>Application Support & Maintenance</a>
                        </li>
                    </ul>
                </li>
                <li class="menu-has-children">
                    <a href="javascript:;">Products/Solutions</a>
                    <ul>
                        <li>
                            <a href='@Url.Action("smart-learning","Home")'>Smart Learning</a>
                        </li>
                        <li>
                            <a href='@Url.Action("smart-jobs","Home")'>Smart Jobs</a>
                        </li>
                    </ul>
                </li>
                <li><a href="@Url.Action("team","Home")">Smart Team</a></li>
                <li><a href="@Url.Action("contact","Home")">Contact</a></li>
                <li><a href="@Url.Action("careers","Home")">Careers</a></li>
                <li><a href="@Url.Action("Login","SmartLearning")" class="btn btn-danger" style="padding:2px 5px 2px 5px;width: 100px;
    margin-left: 10px;">Login</a></li>
            </ul>
        </nav><!-- #nav-menu-container -->
    </div>
</header>

ConnectSmartConsulting/Views/Shared/_Intro.cshtml
<section id="intro">
    <div class="intro-container">
        <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators"></ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active" style="background-image: url('/content/theme_1/img/intro-carousel/1.jpg');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>CONNECT SMART CONSULTING</h2>
                            <p>Your Digital Consulting Partners.</p>
                            <a href="#featured-services" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>
                @*<div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/5.jpg');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>Smart Learning</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/smart-learning")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>*@
                <div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/SoftwareEngineeringServices.jpg');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>Smart Engineering (Agile Practices)</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/software-Engineering")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/reseller_banner_2.jpg');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>Software Resellers</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/software-reseller")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/Sales-Strategy-by-Sales-Strategy-Consulting.jpg');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>Sales &amp; Digital Marketing</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/sales-and-digital-marketing")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/ERPConsulting.png');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>ERP Consulting</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/erp-consulting")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/Application_Support-1030x391.png');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>Application Support &amp; Maintenance</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/application-support-maintenance")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>
                @*<div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/jobs.jpg');">
                    <div class="carousel-container">
                        <div class="carousel-content">
                            <h2>Smart Jobs</h2>
                            <p>&nbsp;</p>
                            <a href="@Url.Content("~/home/smart-jobs")" class="btn-get-started scrollto">Get Started</a>
                        </div>
                    </div>
                </div>*@
                @*<div class="carousel-item" style="background-image: url('/content/theme_1/img/intro-carousel/consulting.jpg');">
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>IT Consulting</h2>
                                    <p>&nbsp;</p>
                                    <a href="@Url.Content("~/home/it-consulting")" class="btn-get-started scrollto">Get Started</a>
                                </div>
                            </div>
                        </div>
                    </div>*@
                <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</section>

ConnectSmartConsulting/Views/Shared/_adminNav.cshtml
<ul id="side-main-menu" class="side-menu list-unstyled">
    <li><a href="@Url.Action("index", "admin")"> <i class="icon-home"></i><span>Home</span></a></li>
    <li id="students"> <a href="@Url.Action("students", "admin")"><i class="icon-form"></i><span>Students</span></a></li>
    <li id="tutors"> <a href="@Url.Action("tutors", "admin")"><i class="icon-presentation"></i><span>Tutors</span></a></li>
    <li id="resources"> <a href="@Url.Action("index", "FreeResources")"> <i class="icon-grid"> </i><span>Free Resources</span></a></li>
    <li id="service"> <a href="@Url.Action("service-enquiry", "admin")"> <i class="icon-interface-windows"></i><span>Service Enquiry </span></a></li>
    <li> <a href="@Url.Action("index", "ServiceRequest")"> <i class="icon-interface-windows"></i><span>Tickets </span></a></li>
    <li id="subscriptions">
        <a href="@Url.Action("subscriptions", "admin")">
            <i class="icon-mail"></i><span>Subscriptions</span>
            @*<div class="badge badge-warning">6 New</div>*@
        </a>
    </li>
    <li> <a href="@Url.Action("sessions", "admin")"> <i class="icon-interface-windows"></i><span>Sessions </span></a></li>
</ul>

ConnectSmartConsulting/Views/Shared/_basicInfo.cshtml
<div class="wrapper count-title d-flex">
    <div class="icon img img-thumbnail">
        <img src="@Url.Action("Image", "Home", new { img = Model.UserDetails[0].ImagePath })" style="max-width:128px" />
    </div>
    <div class="name">
        @if (Session["LOGIN_USER"] != null)
        {
            <strong class="text-uppercase">@Model.UserDetails[0].FirstName @Model.UserDetails[0].LastName</strong>
            <span>@Model.UserDetails[0].CurrentCity</span>
        }
    </div>
</div>

ConnectSmartConsulting/Views/Shared/_tutorNav.cshtml
<ul id="side-main-menu" class="side-menu list-unstyled">
    <li id="tutor"><a href="@Url.Action("index", "tutor")"> <i class="icon-home"></i><span>Home</span></a></li>
    <li id="students"> <a href="@Url.Action("students", "tutor")"><i class="icon-form"></i><span>My Students</span></a></li>
    <li>
        <a id="sessions" href="#pages-nav-list" data-toggle="collapse" aria-expanded="false">
            <i class="icon-interface-windows"></i><span>My Sessions</span>
            <div class="arrow pull-right"><i class="fa fa-angle-down"></i></div>
        </a>
        <ul id="pages-nav-list" class="collapse list-unstyled">
            <li> <a href="@Url.Action("schedule-session", "tutor")">Schedule a Session Now</a></li>
            <li> <a href="@Url.Action("create-schedule", "tutor")">Create a Schedule</a></li>
            <li> <a href="@Url.Action("join-session", "tutor")">Join the Scheduled Session</a></li>
        </ul>
    </li>
    <li>
        <a id="contents" href="#pages-nav-list2" data-toggle="collapse" aria-expanded="false">
            <i class="icon-interface-windows"></i><span>Contents</span>
            <div class="arrow pull-right"><i class="fa fa-angle-down"></i></div>
        </a>
        <ul id="pages-nav-list2" class="collapse list-unstyled">
            <li> <a href="@Url.Action("view-assignments", "tutor")">Manage Assignments</a></li>
            <li> <a href="@Url.Action("add-assignment", "tutor")">Create Assignment for Students</a></li>
            <li> <a href="@Url.Action("publish-result", "tutor")">Publish Results for a single assigned student</a></li>
            <li> <a href="@Url.Action("create-free-material", "tutor")">Create Free Material</a></li>
        </ul>
    </li>
    <li id="myprofile"> <a href="@Url.Action("my-profile", "tutor")"> <i class="icon-grid"> </i><span>My Profile</span></a></li>
    <li id="mytickets"> <a href="@Url.Action("index", "ServiceRequest")"> <i class="icon-interface-windows"></i><span>My Tickets </span></a></li>
</ul>